CREATE TABLE `work_records` (
	`id` text PRIMARY KEY NOT NULL,
	`group_id` text NOT NULL,
	`plan_id` text,
	`slot_id` text,
	`user_email` text NOT NULL,
	`scheduled_date` text NOT NULL,
	`scheduled_start_time` text DEFAULT '' NOT NULL,
	`scheduled_end_time` text DEFAULT '' NOT NULL,
	`started_at` text,
	`ended_at` text,
	`start_network_status` text DEFAULT 'unknown' NOT NULL,
	`end_network_status` text DEFAULT 'unknown' NOT NULL,
	`start_source_ip` text DEFAULT '' NOT NULL,
	`end_source_ip` text DEFAULT '' NOT NULL,
	`start_latitude` text,
	`start_longitude` text,
	`start_accuracy` text,
	`end_latitude` text,
	`end_longitude` text,
	`end_accuracy` text,
	`status` text DEFAULT 'working' NOT NULL,
	`employee_note` text DEFAULT '' NOT NULL,
	`manager_note` text DEFAULT '' NOT NULL,
	`approved_by` text,
	`approved_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
