"use client";
import { useEffect, useState } from "react";
import { localApiFetch } from "./local-api";

type Announcement = { id: string; title: string; body: string; createdBy: string; createdAt: string };
type Reply = { id: string; announcementId: string; userEmail: string; body: string; createdAt: string };
type Props = { groupId: string; manager?: boolean };

export default function AnnouncementsPanel({ groupId, manager = false }: Props) {
  const [items, setItems] = useState<Announcement[]>([]); const [replies, setReplies] = useState<Reply[]>([]); const [reads, setReads] = useState<string[]>([]); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [reply, setReply] = useState<Record<string, string>>({}); const [notice, setNotice] = useState("");
  async function load() { const response = await localApiFetch(`/api/groups/${groupId}/announcements`); if (!response.ok) return; const data = await response.json() as { announcements: Announcement[]; replies: Reply[]; reads: Array<{ announcementId: string }> }; setItems(data.announcements); setReplies(data.replies); setReads(data.reads.map((row) => row.announcementId)); }
  useEffect(() => { void load(); }, [groupId]);
  async function post(action: string, announcementId?: string, text?: string) { const response = await localApiFetch(`/api/groups/${groupId}/announcements`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, announcementId, title, body: text ?? body }) }); setNotice(response.ok ? "保存しました" : "保存できませんでした"); if (response.ok) { setTitle(""); setBody(""); if (announcementId) setReply((current) => ({ ...current, [announcementId]: "" })); await load(); } }
  return <div className="announcements-panel"><div className="modal-head"><div><p className="eyebrow">ANNOUNCEMENTS</p><h2>お知らせ・連絡</h2></div></div>{manager && <form className="announcement-create" onSubmit={(event) => { event.preventDefault(); void post("create"); }}><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="タイトル" /><textarea required rows={3} value={body} onChange={(event) => setBody(event.target.value)} placeholder="メンバーへのお知らせ" /><button className="primary-button">お知らせを作成</button></form>}<div className="announcement-list">{items.length ? items.map((item) => <article className="announcement-item" key={item.id}><div className="announcement-head"><strong>{item.title}</strong><small>{item.createdAt}</small>{!reads.includes(item.id) && <button className="small-action" onClick={() => void post("read", item.id)}>既読にする</button>}</div><p>{item.body}</p><div className="announcement-replies">{replies.filter((row) => row.announcementId === item.id).map((row) => <div key={row.id}><strong>{row.userEmail.split("@")[0]}</strong><span>{row.body}</span></div>)}</div><div className="announcement-reply"><input value={reply[item.id] ?? ""} onChange={(event) => setReply((current) => ({ ...current, [item.id]: event.target.value }))} placeholder={manager ? "返信・補足" : "返信・連絡"} /><button className="small-action" disabled={!reply[item.id]?.trim()} onClick={() => void post(manager ? "reply" : "contact", item.id, reply[item.id])}>{manager ? "返信" : "送信"}</button></div></article>) : <p className="empty-state">お知らせはありません。</p>}</div>{notice && <p className="group-notice">{notice}</p>}</div>;
}
