"use client";

import { useEffect, useState } from "react";
import { localApiFetch } from "./local-api";

type Day = { dayOfWeek: number; status: string; startTime: string; endTime: string; note: string };
type Preference = { minDays: number; maxDays: number; minHours: number; maxHours: number; weekendPolicy: string; freeComment: string };
const labels = ["日", "月", "火", "水", "木", "金", "土"];

export default function GroupPreferencesPanel({ groupId }: { groupId: string }) {
  const [days, setDays] = useState<Record<number, Day>>({});
  const [preference, setPreference] = useState<Preference>({ minDays: 0, maxDays: 7, minHours: 0, maxHours: 40, weekendPolicy: "any", freeComment: "" });
  const [notice, setNotice] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { void localApiFetch(`/api/groups/${groupId}/preferences`).then(async (response) => { if (!response.ok) return; const data = await response.json() as { preferences: Preference; availability: Day[] }; setPreference(data.preferences); setDays(Object.fromEntries(data.availability.map((day) => [day.dayOfWeek, day]))); }); }, 0); return () => window.clearTimeout(timer); }, [groupId]);
  function updateDay(day: number, values: Partial<Day>) { setDays((current) => ({ ...current, [day]: { dayOfWeek: day, status: current[day]?.status ?? "available", startTime: current[day]?.startTime ?? "09:00", endTime: current[day]?.endTime ?? "18:00", note: current[day]?.note ?? "", ...values } })); }
  async function save() { setSaving(true); const response = await localApiFetch(`/api/groups/${groupId}/preferences`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...preference, availability: Object.values(days) }) }); setNotice(response.ok ? "基本設定を保存しました" : "基本設定を保存できませんでした"); setSaving(false); }
  return <div className="group-preferences"><div className="section-title"><div><h4>勤務の基本希望</h4><p>毎週の傾向を登録します。期間ごとの例外はシフト希望で変更できます。</p></div><button className="small-action" onClick={() => void save()} disabled={saving}>{saving ? "保存中…" : "保存"}</button></div><div className="preference-days">{labels.map((label, day) => { const value = days[day] ?? { dayOfWeek: day, status: "available", startTime: "09:00", endTime: "18:00", note: "" }; return <div className="preference-day" key={day}><strong>{label}</strong><select value={value.status} onChange={(event) => updateDay(day, { status: event.target.value })}><option value="available">勤務可能</option><option value="limited">時間指定</option><option value="unavailable">原則不可</option></select>{value.status === "limited" && <div className="time-pair"><input type="time" value={value.startTime} onChange={(event) => updateDay(day, { startTime: event.target.value })} /><input type="time" value={value.endTime} onChange={(event) => updateDay(day, { endTime: event.target.value })} /></div>}</div>; })}</div><div className="preference-fields"><label>週の希望勤務日数（下限）<input type="number" min="0" max="7" value={preference.minDays} onChange={(event) => setPreference({ ...preference, minDays: Number(event.target.value) })} /></label><label>週の希望勤務日数（上限）<input type="number" min="0" max="7" value={preference.maxDays} onChange={(event) => setPreference({ ...preference, maxDays: Number(event.target.value) })} /></label><label>週の希望勤務時間（下限）<input type="number" min="0" max="168" value={preference.minHours} onChange={(event) => setPreference({ ...preference, minHours: Number(event.target.value) })} /></label><label>週の希望勤務時間（上限）<input type="number" min="0" max="168" value={preference.maxHours} onChange={(event) => setPreference({ ...preference, maxHours: Number(event.target.value) })} /></label><label>土日の希望<select value={preference.weekendPolicy} onChange={(event) => setPreference({ ...preference, weekendPolicy: event.target.value })}><option value="any">特になし</option><option value="prefer_off">できれば休み</option><option value="unavailable">勤務不可</option></select></label></div><label className="preference-comment">固定休・授業・本業などのフリーコメント<textarea rows={3} maxLength={500} value={preference.freeComment} onChange={(event) => setPreference({ ...preference, freeComment: event.target.value })} placeholder="例：水曜は授業のため18時以降のみ可能" /></label>{notice && <p className="group-notice" role="status">{notice}</p>}</div>;
}
