"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { localApiFetch } from "./local-api";

type RecordRow = { id: string; userEmail: string; scheduledDate: string; scheduledStartTime: string; scheduledEndTime: string; startedAt?: string | null; endedAt?: string | null; claimedStartAt?: string | null; claimedEndAt?: string | null; startNetworkStatus: string; endNetworkStatus: string; status: string; employeeNote?: string; managerNote?: string };
type ScheduleRow = { id: string; date: string; startTime: string; endTime: string; role?: string; planName: string; userEmail: string; record: RecordRow | null };
type Member = { userEmail: string; displayName?: string | null };
type BreakRow = { id: string; workRecordId: string; startedAt: string; endedAt?: string | null };
type Draft = { start: string; end: string };

function statusLabel(value: string, ended = false) { if (value === "working") return ended ? "未申請" : "勤務中"; return ({ unsubmitted: "未申請", submitted: "承認待ち", approved: "承認済み", rejected: "差戻し" } as Record<string, string>)[value] ?? value; }
function networkLabel(value: string) { return ({ store: "店舗ネットワーク", external: "外部ネットワーク", unknown: "判定不可" } as Record<string, string>)[value] ?? value; }
function formatTime(value?: string | null) { if (!value) return "—"; return new Intl.DateTimeFormat("ja-JP", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function formatClock(value?: string | null) { if (!value) return "—"; return new Intl.DateTimeFormat("ja-JP", { hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function timeOnly(value: string, date: string) {
  if (!value) return "";
  const base = new Date(`${date}T00:00:00+09:00`).getTime();
  const minutes = Math.round((new Date(value).getTime() - base) / 60000);
  if (!Number.isFinite(minutes)) return "";
  return `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`;
}
function withDate(date: string, value: string) {
  const match = /^(\d{1,2}):(\d{2})$/.exec(value.trim());
  if (!match) return "";
  const hours = Number(match[1]); const minutes = Number(match[2]);
  if (hours < 0 || hours > 30 || minutes > 59) return "";
  const base = new Date(`${date}T00:00:00+09:00`); base.setMinutes(hours * 60 + minutes);
  const parts = new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(base);
  const get = (type: string) => parts.find((part) => part.type === type)?.value ?? "";
  return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`;
}
function todayKey() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tokyo" }).format(new Date()); }
const timeOptions = Array.from({ length: 61 }, (_, index) => { const total = index * 30; const hour = Math.floor(total / 60); const minute = total % 60; const value = String(hour).padStart(2, "0") + ":" + String(minute).padStart(2, "0"); const next = hour >= 24 ? "（翌" + String(hour - 24).padStart(2, "0") + ":" + String(minute).padStart(2, "0") + "）" : ""; return { value, label: value + next }; });
function TimeSelect({ value, date, label, onChange, disabled = false }: { value: string; date: string; label: string; onChange: (value: string) => void; disabled?: boolean }) { return <select className="claim-time-select" aria-label={label} value={timeOnly(value, date)} disabled={disabled} onChange={(event) => onChange(withDate(date, event.target.value))}><option value="">--:--</option>{timeOptions.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select>; }
function localDateTime(value?: string | null) { if (!value) return ""; const parts = new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(new Date(value)); const get = (type: string) => parts.find((part) => part.type === type)?.value ?? ""; return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`; }
function monthKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; }
function daysForMonth(key: string) { const [year, month] = key.split("-").map(Number); const count = new Date(year, month, 0).getDate(); return Array.from({ length: count }, (_, index) => `${key}-${String(index + 1).padStart(2, "0")}`); }
function monthLabel(key: string) { const [year, month] = key.split("-").map(Number); return `${year}年${month}月`; }
function dayLabel(date: string) { const day = new Date(`${date}T00:00:00+09:00`); return `${Number(date.slice(8, 10))}日（${"日月火水木金土"[day.getDay()]}）`; }
function breakMinutes(rows: BreakRow[]) { return rows.reduce((total, item) => item.endedAt ? total + Math.max(0, Math.round((new Date(item.endedAt).getTime() - new Date(item.startedAt).getTime()) / 60000)) : total, 0); }
function workedMinutes(row: RecordRow, breaks: BreakRow[]) { if (!row.startedAt || !row.endedAt) return null; return Math.max(0, Math.round((new Date(row.endedAt).getTime() - new Date(row.startedAt).getTime()) / 60000) - breakMinutes(breaks)); }
function requestLocationIfNeeded(network: string) { if (network !== "external" || typeof navigator === "undefined" || !navigator.geolocation) return Promise.resolve(undefined); return new Promise<{ latitude: number; longitude: number; accuracy: number } | undefined>((resolve) => navigator.geolocation.getCurrentPosition((position) => resolve({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy }), () => resolve(undefined), { enableHighAccuracy: false, timeout: 8000, maximumAge: 60000 })); }

export default function WorkRecordsPanel({ groupId, manager = false }: { groupId: string; manager?: boolean }) {
  const [groupName, setGroupName] = useState(""); const [network, setNetwork] = useState("unknown"); const [records, setRecords] = useState<RecordRow[]>([]); const [breaks, setBreaks] = useState<BreakRow[]>([]); const [schedule, setSchedule] = useState<ScheduleRow[]>([]); const [members, setMembers] = useState<Member[]>([]); const [claimDrafts, setClaimDrafts] = useState<Record<string, Draft>>({}); const [manualDrafts, setManualDrafts] = useState<Record<string, Draft>>({}); const [month, setMonth] = useState(monthKey(new Date())); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const saveTimers = useRef<Record<string, ReturnType<typeof setTimeout>>>({});
  async function load() { setBusy(true); const response = await localApiFetch(`/api/groups/${groupId}/work-records`); if (response.ok) { const data = await response.json() as { group?: { name?: string }; currentNetworkStatus?: string; records?: RecordRow[]; breaks?: BreakRow[]; schedule?: ScheduleRow[]; members?: Member[] }; const nextRecords = data.records ?? []; setGroupName(data.group?.name ?? ""); setNetwork(data.currentNetworkStatus ?? "unknown"); setRecords(nextRecords); setBreaks(data.breaks ?? []); setSchedule(data.schedule ?? []); setMembers(data.members ?? []); setClaimDrafts(Object.fromEntries(nextRecords.map((record) => [record.id, { start: localDateTime(record.claimedStartAt ?? record.startedAt), end: localDateTime(record.claimedEndAt ?? record.endedAt) }]))); setNotice(""); } else setNotice("勤務状況を読み込めませんでした。"); setBusy(false); }
  useEffect(() => { void load(); return () => Object.values(saveTimers.current).forEach(clearTimeout); }, [groupId]);
  async function start(slotId?: string) { setBusy(true); const location = await requestLocationIfNeeded(network); const response = await localApiFetch(`/api/groups/${groupId}/work-records`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "start", slotId, location }) }); setNotice(response.ok ? "勤務開始を記録しました。" : ((await response.json().catch(() => ({}))) as { error?: string }).error ?? "勤務開始を記録できませんでした。"); if (response.ok) await load(); else setBusy(false); }
  async function end(record: RecordRow) { if (!window.confirm("勤務終了を記録しますか？")) return; setBusy(true); const location = await requestLocationIfNeeded(network); const response = await localApiFetch(`/api/groups/${groupId}/work-records`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "end", recordId: record.id, location }) }); setNotice(response.ok ? "勤務終了を記録しました。申告時間を確認して申請してください。" : "勤務終了を記録できませんでした。"); if (response.ok) await load(); else setBusy(false); }
  async function toggleBreak(record: RecordRow, action: "break-start" | "break-end") { const response = await localApiFetch(`/api/groups/${groupId}/work-records`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, recordId: record.id }) }); setNotice(response.ok ? (action === "break-start" ? "休憩開始を記録しました。" : "休憩終了を記録しました。") : "休憩記録を更新できませんでした。"); if (response.ok) await load(); }
  async function patch(body: Record<string, unknown>) { return localApiFetch(`/api/groups/${groupId}/work-records`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); }
  async function review(recordId: string, status: "approved" | "rejected") { const response = await patch({ recordId, status }); setNotice(response.ok ? (status === "approved" ? "勤務記録を承認しました。" : "勤務記録を差し戻しました。") : "勤務記録を更新できませんでした。"); if (response.ok) await load(); }
  async function saveClaim(record: RecordRow, draft = claimDrafts[record.id]) { if (!draft?.start) return; const response = await patch({ action: "save-claim", recordId: record.id, claimedStartAt: draft.start, claimedEndAt: draft.end }); if (!response.ok) setNotice(((await response.json().catch(() => ({}))) as { error?: string }).error ?? "申告時間を保存できませんでした。"); }
  function updateDraft(record: RecordRow, next: Draft) { setClaimDrafts((current) => ({ ...current, [record.id]: next })); clearTimeout(saveTimers.current[record.id]); saveTimers.current[record.id] = setTimeout(() => void saveClaim(record, next), 500); }
  async function applySchedule(record: RecordRow) { const response = await patch({ action: "apply-schedule", recordId: record.id }); setNotice(response.ok ? "シフトの予定時刻を申告時間に反映しました。内容を確認して申請してください。" : "シフト時刻を反映できませんでした。"); if (response.ok) await load(); }
  async function createClaim(slot: ScheduleRow) { const response = await localApiFetch(`/api/groups/${groupId}/work-records`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create-claim", slotId: slot.id, claimedStartAt: `${slot.date}T${slot.startTime}`, claimedEndAt: `${slot.date}T${slot.endTime}` }) }); setNotice(response.ok ? "過去の勤務申告を作成しました。内容を確認して申請してください。" : "勤務申告を作成できませんでした。"); if (response.ok) await load(); }
  async function createManualClaim(date: string, draft: Draft) { if (!draft.start || !draft.end) return; const response = await localApiFetch(`/api/groups/${groupId}/work-records`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create-manual-claim", scheduledDate: date, claimedStartAt: draft.start, claimedEndAt: draft.end }) }); setNotice(response.ok ? "勤務申告を作成しました。内容を確認して申請してください。" : "勤務申告を作成できませんでした。"); if (response.ok) await load(); }
  function updateManualDraft(date: string, next: Draft) { setManualDrafts((current) => ({ ...current, [date]: next })); if (next.start && next.end) void createManualClaim(date, next); }
  async function submit(record: RecordRow) { const draft = claimDrafts[record.id]; if (!draft?.start || !draft.end) { setNotice("開始・終了の申告時間を入力してください。"); return; } const response = await patch({ action: "submit-claim", recordId: record.id, claimedStartAt: draft.start, claimedEndAt: draft.end }); if (response.status === 409) { const data = await response.json().catch(() => ({})) as { error?: string }; if (!window.confirm(`${data.error ?? "シフト予定と大きく異なります。"}\nこの内容で申請しますか？`)) return; const confirmed = await patch({ action: "submit-claim", recordId: record.id, claimedStartAt: draft.start, claimedEndAt: draft.end, confirm: true }); setNotice(confirmed.ok ? "勤務記録を申請しました。" : "勤務記録を申請できませんでした。"); if (confirmed.ok) await load(); return; } setNotice(response.ok ? "勤務記録を申請しました。" : ((await response.json().catch(() => ({}))) as { error?: string }).error ?? "勤務記録を申請できませんでした。"); if (response.ok) await load(); }

  const names = useMemo(() => new Map(members.map((member) => [member.userEmail, member.displayName?.trim() || member.userEmail.split("@")[0]])), [members]); const breaksFor = (id: string) => breaks.filter((item) => item.workRecordId === id); const activeRecords = records.filter((record) => record.status === "working" && !record.endedAt); const pendingRecords = records.filter((record) => record.status === "submitted"); const days = daysForMonth(month); const recordsByDate = useMemo(() => new Map(records.map((record) => [record.scheduledDate, record])), [records]); const schedulesByDate = useMemo(() => new Map(schedule.map((item) => [item.date, item])), [schedule]);
  function moveMonth(offset: number) { const [year, current] = month.split("-").map(Number); const date = new Date(year, current - 1 + offset, 1); setMonth(monthKey(date)); }
  const today = todayKey();
  return <section className="work-records-panel">
    <div className="modal-head"><div><p className="eyebrow">WORK RECORDS</p><h2>{manager ? "勤務状況の確認" : "勤務状況"}{groupName ? `（${groupName}）` : ""}</h2></div></div>
    <div className="work-records-status"><span>{networkLabel(network)}</span>{network === "external" && <span>店舗ネットワーク外のため、開始・終了時に位置情報を任意で取得します。</span>}{network === "unknown" && <span>店舗ネットワークの登録がないため、通信判定は参考情報です。</span>}</div>
    {manager ? <ManagerView records={records} members={members} breaksFor={breaksFor} activeRecords={activeRecords} pendingRecords={pendingRecords} review={review} /> : <>
      <div className="work-month-toolbar">
        <button className="small-action" onClick={() => moveMonth(-1)}>前月</button>
        <select aria-label="表示月" value={month} onChange={(event) => setMonth(event.target.value)}>{Array.from({ length: 13 }, (_, index) => { const date = new Date(); date.setMonth(date.getMonth() - 6 + index, 1); const key = monthKey(date); return <option value={key} key={key}>{monthLabel(key)}</option>; })}</select>
        <button className="small-action" onClick={() => moveMonth(1)}>次月</button>
        <button className="primary-button" disabled={busy} onClick={() => void start()}>勤務開始</button>
      </div>
      <p className="work-month-help">日付に関係なく当月の勤務記録を表示します。入力内容は変更時に自動保存されます。</p>
      <div className="monthly-work-wrap work-records-table-wrap"><table className="work-records-table monthly-work-table"><thead><tr><th>日付</th><th>シフト予定</th><th>打刻</th><th>申告時間</th><th>休憩</th><th>状態</th><th>操作</th></tr></thead><tbody>
        {days.map((date) => {
          const record = recordsByDate.get(date);
          const planned = schedulesByDate.get(date);
          const draft = record ? claimDrafts[record.id] ?? { start: localDateTime(record.claimedStartAt ?? record.startedAt), end: localDateTime(record.claimedEndAt ?? record.endedAt) } : null;
          const manual = manualDrafts[date] ?? { start: "", end: "" };
          const onBreak = record ? breaksFor(record.id).some((item) => !item.endedAt) : false;
          const past = date <= today;
          return <tr key={date}>
            <th>{dayLabel(date)}</th>
            <td>{planned ? <><span className="monthly-shift-ref">{planned.startTime}〜{planned.endTime}</span>{record ? record.status !== "approved" && <button className="small-action" disabled={busy} onClick={() => void applySchedule(record)}>シフト通り</button> : past ? <button className="small-action" disabled={busy} onClick={() => void createClaim(planned)}>シフト通り</button> : null}</> : <span className="monthly-record-value">対象なし</span>}</td>
            <td>{record ? <span className="monthly-record-value">{formatClock(record.startedAt)}〜{formatClock(record.endedAt)}</span> : <span className="monthly-record-value">—</span>}</td>
            <td>{record ? <div className="claim-time-fields monthly-claim"><TimeSelect value={draft?.start ?? ""} date={date} label={`${date} 申告開始`} disabled={record.status === "approved"} onChange={(value) => updateDraft(record, { start: value, end: draft?.end ?? "" })} /><span>〜</span><TimeSelect value={draft?.end ?? ""} date={date} label={`${date} 申告終了`} disabled={record.status === "approved"} onChange={(value) => updateDraft(record, { start: draft?.start ?? "", end: value })} /></div> : past ? <div className="claim-time-fields monthly-claim"><TimeSelect value={manual.start} date={date} label={`${date} 申告開始`} onChange={(value) => updateManualDraft(date, { start: value, end: manual.end })} /><span>〜</span><TimeSelect value={manual.end} date={date} label={`${date} 申告終了`} onChange={(value) => updateManualDraft(date, { start: manual.start, end: value })} /></div> : "—"}</td>
            <td>{record ? `${breakMinutes(breaksFor(record.id))}分` : "—"}{record && onBreak && <small>休憩中</small>}</td>
            <td>{record ? <span className={"work-status work-status-" + record.status}>{statusLabel(record.status, Boolean(record.endedAt))}</span> : planned ? <span className="work-status work-status-unsubmitted">未申告</span> : <span className="work-status work-status-none">—</span>}</td>
            <td>{record ? <span className="monthly-actions">{["working", "unsubmitted"].includes(record.status) && (record.endedAt || draft?.end) && <button className="small-action" disabled={busy} onClick={() => void submit(record)}>申請</button>}{record.status === "working" && !record.endedAt && record.startedAt && <><button className="small-action" disabled={busy} onClick={() => void toggleBreak(record, onBreak ? "break-end" : "break-start")}>{onBreak ? "休憩終了" : "休憩開始"}</button>{!onBreak && <button className="small-action" disabled={busy} onClick={() => void end(record)}>勤務終了</button>}</>}</span> : planned && date > today ? <button className="small-action" disabled={busy} onClick={() => void start(planned.id)}>勤務開始</button> : "—"}</td>
          </tr>;
        })}
      </tbody></table></div>
    </>}</section>;
  }

function ManagerView({ records, members, breaksFor, activeRecords, pendingRecords, review }: { records: RecordRow[]; members: Member[]; breaksFor: (id: string) => BreakRow[]; activeRecords: RecordRow[]; pendingRecords: RecordRow[]; review: (id: string, status: "approved" | "rejected") => Promise<void> }) { const names = new Map(members.map((member) => [member.userEmail, member.displayName?.trim() || member.userEmail.split("@")[0]])); return <><div className="work-records-summary"><strong>承認待ち {pendingRecords.length}件</strong><span>勤務中 {activeRecords.length}件</span></div><div className="work-records-table-wrap"><table className="work-records-table"><thead><tr><th>日付</th><th>メンバー</th><th>予定</th><th>実績</th><th>休憩</th><th>通信</th><th>状態</th><th>操作</th></tr></thead><tbody>{records.length ? records.map((record) => <tr key={record.id}><td>{record.scheduledDate}</td><td>{names.get(record.userEmail) ?? record.userEmail.split("@")[0]}</td><td>{record.scheduledStartTime || "—"}〜{record.scheduledEndTime || "—"}</td><td>{formatTime(record.startedAt)}〜{formatTime(record.endedAt)}{workedMinutes(record, breaksFor(record.id)) !== null && <small>実働 {workedMinutes(record, breaksFor(record.id))}分</small>}</td><td>{breakMinutes(breaksFor(record.id))}分</td><td>{networkLabel(record.startNetworkStatus)} / {networkLabel(record.endNetworkStatus)}</td><td><span className={`work-status work-status-${record.status}`}>{statusLabel(record.status, Boolean(record.endedAt))}</span></td><td>{record.status === "submitted" ? <span className="work-review-actions"><button className="small-action" onClick={() => void review(record.id, "approved")}>承認</button><button className="small-action" onClick={() => void review(record.id, "rejected")}>差戻し</button></span> : "—"}</td></tr>) : <tr><td colSpan={8}>勤務記録はまだありません。</td></tr>}</tbody></table></div></>; }
