import { and, desc, eq, inArray } from "drizzle-orm";
import { getDb } from "../../db";
import {
  accountProfiles,
  announcementReads,
  announcementReplies,
  events,
  groupAnnouncements,
  groupJoinRequests,
  groupMembers,
  groupPreferences,
  groups,
  shiftAssignments,
  shiftAvailability,
  shiftPlans,
  shiftRequestPeriods,
  shiftRequests,
  shiftSlots,
} from "../../db/schema";
import { requireApiIdentity } from "../api/api-auth";
import { canViewAdminNote, toPublicMember } from "../api/groups/member-dto";

export const dynamic = "force-dynamic";

type Args = Record<string, unknown>;
type RpcRequest = { jsonrpc?: string; id?: string | number | null; method?: string; params?: { name?: string; arguments?: Args } };
const mutating = "This operation changes saved data. Re-run with confirm:true after confirming the target and scope.";
const editorRoles = new Set(["owner", "editor"]);
const preferenceValues = new Set(["want", "possible", "off", "unavailable"]);

const tools = [
  { name: "list_my_tasks", description: "List the authenticated user's personal tasks.", inputSchema: { type: "object", properties: { from: { type: "string" }, to: { type: "string" } } } },
  { name: "create_task", description: "Create a personal task.", inputSchema: { type: "object", required: ["title", "date"], properties: { title: { type: "string" }, date: { type: "string" }, startTime: { type: "string" }, endTime: { type: "string" }, category: { type: "string", enum: ["仕事", "生活", "予定"] }, notes: { type: "string" } } } },
  { name: "update_task", description: "Update a personal task. Requires confirm:true.", inputSchema: { type: "object", required: ["id", "confirm"], properties: { id: { type: "string" }, confirm: { type: "boolean" }, title: { type: "string" }, date: { type: "string" }, startTime: { type: "string" }, endTime: { type: "string" }, category: { type: "string" }, notes: { type: "string" }, completed: { type: "boolean" } } } },
  { name: "delete_task", description: "Delete a personal task. Requires confirm:true.", inputSchema: { type: "object", required: ["id", "confirm"], properties: { id: { type: "string" }, confirm: { type: "boolean" } } } },
  { name: "list_groups", description: "List groups where the authenticated user is a member.", inputSchema: { type: "object", properties: {} } },
  { name: "get_profile", description: "Get the authenticated account nickname.", inputSchema: { type: "object", properties: {} } },
  { name: "set_profile_nickname", description: "Change the authenticated account nickname. Requires confirm:true.", inputSchema: { type: "object", required: ["nickname", "confirm"], properties: { nickname: { type: "string" }, confirm: { type: "boolean" } } } },
  { name: "get_group_members", description: "List members and group-local nicknames.", inputSchema: { type: "object", required: ["groupId"], properties: { groupId: { type: "string" } } } },
  { name: "update_group_member", description: "Change a group-local nickname, visibility, or role. Requires confirm:true.", inputSchema: { type: "object", required: ["groupId", "userEmail", "confirm"], properties: { groupId: { type: "string" }, userEmail: { type: "string" }, displayName: { type: "string" }, showInPersonal: { type: "boolean" }, role: { type: "string", enum: ["owner", "editor", "member"] }, confirm: { type: "boolean" } } } },
  { name: "list_join_requests", description: "List pending and past join requests. Owner only.", inputSchema: { type: "object", required: ["groupId"], properties: { groupId: { type: "string" } } } },
  { name: "decide_join_request", description: "Approve or reject a join request. Requires owner role and confirm:true.", inputSchema: { type: "object", required: ["groupId", "requestId", "action", "confirm"], properties: { groupId: { type: "string" }, requestId: { type: "string" }, action: { type: "string", enum: ["approve", "reject"] }, confirm: { type: "boolean" } } } },
  { name: "get_group_preferences", description: "Get the authenticated member's basic work preferences and weekly availability.", inputSchema: { type: "object", required: ["groupId"], properties: { groupId: { type: "string" } } } },
  { name: "save_group_preferences", description: "Save basic work preferences. Requires confirm:true.", inputSchema: { type: "object", required: ["groupId", "confirm"], properties: { groupId: { type: "string" }, confirm: { type: "boolean" }, minDays: { type: "number" }, maxDays: { type: "number" }, minHours: { type: "number" }, maxHours: { type: "number" }, weekendPolicy: { type: "string" }, freeComment: { type: "string" }, availability: { type: "array" } } } },
  { name: "list_shift_plans", description: "List work-slot plans for a group.", inputSchema: { type: "object", required: ["groupId"], properties: { groupId: { type: "string" } } } },
  { name: "get_shift_plan", description: "Get a plan, its slots, and assignments.", inputSchema: { type: "object", required: ["planId"], properties: { planId: { type: "string" } } } },
  { name: "create_shift_plan", description: "Create a work-slot plan and request period. Requires editor role and confirm:true.", inputSchema: { type: "object", required: ["groupId", "name", "startDate", "endDate", "confirm"], properties: { groupId: { type: "string" }, name: { type: "string" }, startDate: { type: "string" }, endDate: { type: "string" }, openingTime: { type: "string" }, closingTime: { type: "string" }, slotMinutes: { type: "number" }, notes: { type: "string" }, slotRules: { type: "array" }, requestPeriod: { type: "object" }, confirm: { type: "boolean" } } } },
  { name: "delete_draft_shift_plan", description: "Delete a draft plan and its slots. Published plans cannot be deleted. Requires confirm:true.", inputSchema: { type: "object", required: ["planId", "confirm"], properties: { planId: { type: "string" }, confirm: { type: "boolean" } } } },
  { name: "update_slot_counts", description: "Adjust required counts or close/reopen dates in a draft plan. Requires confirm:true.", inputSchema: { type: "object", required: ["planId", "confirm"], properties: { planId: { type: "string" }, confirm: { type: "boolean" }, slots: { type: "array" }, closedDates: { type: "array" } } } },
  { name: "get_shift_requests", description: "Get the authenticated user's shift requests for a request period.", inputSchema: { type: "object", required: ["groupId"], properties: { groupId: { type: "string" }, periodId: { type: "string" } } } },
  { name: "save_shift_requests", description: "Replace the authenticated user's shift requests. Requires confirm:true.", inputSchema: { type: "object", required: ["groupId", "periodId", "requests", "confirm"], properties: { groupId: { type: "string" }, periodId: { type: "string" }, requests: { type: "array" }, confirm: { type: "boolean" } } } },
  { name: "set_shift_assignments", description: "Replace assignments and optionally publish a plan. Requires editor role and confirm:true.", inputSchema: { type: "object", required: ["planId", "assignments", "confirm"], properties: { planId: { type: "string" }, assignments: { type: "object" }, status: { type: "string", enum: ["draft", "published"] }, confirm: { type: "boolean" } } } },
  { name: "list_announcements", description: "List group announcements, read states, and replies.", inputSchema: { type: "object", required: ["groupId"], properties: { groupId: { type: "string" } } } },
  { name: "mark_announcement_read", description: "Mark a group announcement as read.", inputSchema: { type: "object", required: ["announcementId"], properties: { announcementId: { type: "string" } } } },
  { name: "create_announcement", description: "Create a group announcement. Requires editor role and confirm:true.", inputSchema: { type: "object", required: ["groupId", "title", "body", "confirm"], properties: { groupId: { type: "string" }, title: { type: "string" }, body: { type: "string" }, confirm: { type: "boolean" } } } },
  { name: "reply_announcement", description: "Reply to a group announcement.", inputSchema: { type: "object", required: ["announcementId", "body"], properties: { announcementId: { type: "string" }, body: { type: "string" } } } },
  { name: "group_dashboard", description: "Get group member, plan, assignment, and announcement counts.", inputSchema: { type: "object", required: ["groupId"], properties: { groupId: { type: "string" } } } },
];

function text(value: unknown, fallback = "") { return typeof value === "string" ? value.trim() : fallback; }
function rpc(id: RpcRequest["id"], value: unknown) { return Response.json({ jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(value, null, 2) }] } }); }
function rpcError(id: RpcRequest["id"], message: string) { return Response.json({ jsonrpc: "2.0", id, result: { isError: true, content: [{ type: "text", text: message }] } }); }
async function membership(db: ReturnType<typeof getDb>, groupId: string, email: string) { const [row] = await db.select().from(groupMembers).where(and(eq(groupMembers.groupId, groupId), eq(groupMembers.userEmail, email))).limit(1); return row; }
async function planFor(db: ReturnType<typeof getDb>, planId: string, email: string) { const [plan] = await db.select().from(shiftPlans).where(eq(shiftPlans.id, planId)).limit(1); if (!plan) return { error: "Shift plan not found" as const }; const member = await membership(db, plan.groupId, email); if (!member) return { error: "Group membership required" as const }; return { plan, member };
}

export async function POST(request: Request) {
  const identity = await requireApiIdentity(request); if (identity instanceof Response) return identity;
  const payload = await request.json().catch(() => ({})) as RpcRequest;
  if (payload.method === "initialize") return Response.json({ jsonrpc: "2.0", id: payload.id, result: { protocolVersion: "2025-03-26", capabilities: { tools: {} }, serverInfo: { name: "my-day", version: "1.1.0" } } });
  if (payload.method === "notifications/initialized") return new Response(null, { status: 202 });
  if (payload.method === "tools/list") return Response.json({ jsonrpc: "2.0", id: payload.id, result: { tools } });
  if (payload.method !== "tools/call" || !payload.params?.name) return Response.json({ jsonrpc: "2.0", id: payload.id, error: { code: -32601, message: "Unsupported MCP method" } }, { status: 400 });
  const name = payload.params.name; const args = payload.params.arguments ?? {}; const db = getDb();
  try {
    if (name === "list_my_tasks") { const rows = await db.select().from(events).where(eq(events.ownerEmail, identity.email)); return rpc(payload.id, rows.filter((row) => (!args.from || row.date >= String(args.from)) && (!args.to || row.date <= String(args.to)))); }
    if (name === "create_task") { const title = text(args.title); const date = text(args.date); const category = text(args.category, "予定"); if (!title || !date) return rpcError(payload.id, "title and date are required"); if (!["仕事", "生活", "予定"].includes(category)) return rpcError(payload.id, "category must be 仕事, 生活, or 予定"); const row = { id: crypto.randomUUID(), ownerEmail: identity.email, title, date, startTime: text(args.startTime), endTime: text(args.endTime), category, notes: text(args.notes), completed: false }; await db.insert(events).values(row); return rpc(payload.id, row); }
    if (name === "update_task" || name === "delete_task") { if (args.confirm !== true) return rpcError(payload.id, mutating); const id = text(args.id); const [row] = await db.select().from(events).where(and(eq(events.id, id), eq(events.ownerEmail, identity.email))).limit(1); if (!row) return rpcError(payload.id, "Task not found"); if (name === "delete_task") { await db.delete(events).where(eq(events.id, id)); return rpc(payload.id, { ok: true, id }); } const next = { title: args.title === undefined ? row.title : text(args.title), date: args.date === undefined ? row.date : text(args.date), startTime: args.startTime === undefined ? row.startTime : text(args.startTime), endTime: args.endTime === undefined ? row.endTime : text(args.endTime), category: args.category === undefined ? row.category : text(args.category), notes: args.notes === undefined ? row.notes : text(args.notes), completed: args.completed === undefined ? row.completed : Boolean(args.completed) }; await db.update(events).set(next).where(eq(events.id, id)); return rpc(payload.id, { ...row, ...next }); }
    if (name === "list_groups") { const ms = await db.select().from(groupMembers).where(eq(groupMembers.userEmail, identity.email)); const gs = ms.length ? await db.select().from(groups).where(inArray(groups.id, ms.map((m) => m.groupId))) : []; return rpc(payload.id, gs.map((g) => ({ ...g, role: ms.find((m) => m.groupId === g.id)?.role }))); }
    if (name === "get_profile") { const [profile] = await db.select().from(accountProfiles).where(eq(accountProfiles.userEmail, identity.email)).limit(1); return rpc(payload.id, { email: identity.email, nickname: profile?.nickname ?? "" }); }
    if (name === "set_profile_nickname") { if (args.confirm !== true) return rpcError(payload.id, mutating); const nickname = text(args.nickname); if (nickname.length > 40) return rpcError(payload.id, "nickname must be 40 characters or fewer"); const [profile] = await db.select().from(accountProfiles).where(eq(accountProfiles.userEmail, identity.email)).limit(1); if (profile) await db.update(accountProfiles).set({ nickname }).where(eq(accountProfiles.userEmail, identity.email)); else await db.insert(accountProfiles).values({ userEmail: identity.email, nickname }); return rpc(payload.id, { ok: true, nickname }); }
    if (name === "get_group_members") { const groupId = text(args.groupId); const self = await membership(db, groupId, identity.email); if (!self) return rpcError(payload.id, "Group membership required"); const ms = await db.select().from(groupMembers).where(eq(groupMembers.groupId, groupId)); const profiles = ms.length ? await db.select().from(accountProfiles).where(inArray(accountProfiles.userEmail, ms.map((m) => m.userEmail))) : []; return rpc(payload.id, ms.map((m) => ({ ...toPublicMember(m, canViewAdminNote(self.role)), accountNickname: profiles.find((p) => p.userEmail === m.userEmail)?.nickname ?? "" }))); }
    if (name === "update_group_member") { if (args.confirm !== true) return rpcError(payload.id, mutating); const groupId = text(args.groupId); const self = await membership(db, groupId, identity.email); const targetEmail = text(args.userEmail); const target = await membership(db, groupId, targetEmail); if (!self || !target) return rpcError(payload.id, "Group member not found"); if (self.role !== "owner" && targetEmail !== identity.email) return rpcError(payload.id, "Owner permission required"); if (args.displayName !== undefined && targetEmail !== identity.email) return rpcError(payload.id, "Group nickname can only be changed by the member"); if (args.role !== undefined && self.role !== "owner") return rpcError(payload.id, "Only the owner can change permissions"); if (args.role === "owner" && targetEmail !== identity.email) return rpcError(payload.id, "Owner transfer requires a dedicated operation"); if (args.role !== undefined && args.role !== "editor" && args.role !== "member") return rpcError(payload.id, "Invalid group role"); await db.update(groupMembers).set({ ...(args.displayName !== undefined ? { displayName: text(args.displayName).slice(0, 40) } : {}), ...(typeof args.showInPersonal === "boolean" ? { showInPersonal: args.showInPersonal } : {}), ...(typeof args.role === "string" ? { role: args.role as "owner" | "editor" | "member" } : {}) }).where(and(eq(groupMembers.groupId, groupId), eq(groupMembers.userEmail, targetEmail))); return rpc(payload.id, { ok: true }); }
    if (name === "list_join_requests") { const groupId = text(args.groupId); const group = await db.select().from(groups).where(eq(groups.id, groupId)).limit(1); if (!group[0] || group[0].ownerEmail !== identity.email) return rpcError(payload.id, "Owner permission required"); return rpc(payload.id, await db.select().from(groupJoinRequests).where(eq(groupJoinRequests.groupId, groupId))); }
    if (name === "decide_join_request") { if (args.confirm !== true) return rpcError(payload.id, mutating); const groupId = text(args.groupId); const group = await db.select().from(groups).where(eq(groups.id, groupId)).limit(1); if (!group[0] || group[0].ownerEmail !== identity.email) return rpcError(payload.id, "Owner permission required"); const requestId = text(args.requestId); const [joinRequest] = await db.select().from(groupJoinRequests).where(and(eq(groupJoinRequests.id, requestId), eq(groupJoinRequests.groupId, groupId))).limit(1); if (!joinRequest) return rpcError(payload.id, "Join request not found"); const status = args.action === "approve" ? "approved" : "rejected"; const statements = [db.update(groupJoinRequests).set({ status }).where(eq(groupJoinRequests.id, requestId))]; if (status === "approved") statements.push(db.insert(groupMembers).values({ id: crypto.randomUUID(), groupId, userEmail: joinRequest.userEmail, role: "member", showInPersonal: true })); await db.batch(statements); return rpc(payload.id, { ok: true, status }); }
    if (name === "get_group_preferences") { const groupId = text(args.groupId); if (!await membership(db, groupId, identity.email)) return rpcError(payload.id, "Group membership required"); const [preferences] = await db.select().from(groupPreferences).where(and(eq(groupPreferences.groupId, groupId), eq(groupPreferences.userEmail, identity.email))).limit(1); const availability = await db.select().from(shiftAvailability).where(and(eq(shiftAvailability.groupId, groupId), eq(shiftAvailability.userEmail, identity.email))); return rpc(payload.id, { preferences: preferences ?? null, availability }); }
    if (name === "save_group_preferences") { if (args.confirm !== true) return rpcError(payload.id, mutating); const groupId = text(args.groupId); if (!await membership(db, groupId, identity.email)) return rpcError(payload.id, "Group membership required"); const values = { minDays: Number(args.minDays ?? 0), maxDays: Number(args.maxDays ?? 7), minHours: Number(args.minHours ?? 0), maxHours: Number(args.maxHours ?? 40), weekendPolicy: text(args.weekendPolicy, "any"), freeComment: text(args.freeComment).slice(0, 2000) }; const [old] = await db.select().from(groupPreferences).where(and(eq(groupPreferences.groupId, groupId), eq(groupPreferences.userEmail, identity.email))).limit(1); if (old) await db.update(groupPreferences).set(values).where(eq(groupPreferences.id, old.id)); else await db.insert(groupPreferences).values({ id: crypto.randomUUID(), groupId, userEmail: identity.email, ...values }); const entries = Array.isArray(args.availability) ? args.availability as Array<Record<string, unknown>> : []; await db.batch([db.delete(shiftAvailability).where(and(eq(shiftAvailability.groupId, groupId), eq(shiftAvailability.userEmail, identity.email))), ...entries.filter((e) => Number.isInteger(e.dayOfWeek) && ["available", "limited", "unavailable"].includes(text(e.status))).map((e) => db.insert(shiftAvailability).values({ id: crypto.randomUUID(), groupId, userEmail: identity.email, dayOfWeek: Number(e.dayOfWeek), status: text(e.status), startTime: text(e.startTime), endTime: text(e.endTime), note: text(e.note) }))]); return rpc(payload.id, { ok: true }); }
    if (name === "list_shift_plans") { const groupId = text(args.groupId); if (!await membership(db, groupId, identity.email)) return rpcError(payload.id, "Group membership required"); return rpc(payload.id, await db.select().from(shiftPlans).where(eq(shiftPlans.groupId, groupId)).orderBy(desc(shiftPlans.startDate))); }
    if (name === "get_shift_plan") { const found = await planFor(db, text(args.planId), identity.email); if ("error" in found) return rpcError(payload.id, found.error); const slots = await db.select().from(shiftSlots).where(eq(shiftSlots.planId, found.plan.id)); const assignments = slots.length ? await db.select().from(shiftAssignments).where(inArray(shiftAssignments.slotId, slots.map((s) => s.id))) : []; return rpc(payload.id, { plan: found.plan, slots, assignments }); }
    if (name === "create_shift_plan") { if (args.confirm !== true) return rpcError(payload.id, mutating); const groupId = text(args.groupId); const member = await membership(db, groupId, identity.email); if (!member || !editorRoles.has(member.role)) return rpcError(payload.id, "Editor membership required"); const startDate = text(args.startDate); const endDate = text(args.endDate); const openingTime = text(args.openingTime, "09:00"); const closingTime = text(args.closingTime, "18:00"); const slotMinutes = Number(args.slotMinutes ?? 60); const rules = (Array.isArray(args.slotRules) ? args.slotRules : [{ role: "", requiredCount: 1 }]) as Array<Record<string, unknown>>; if (!text(args.name) || !startDate || !endDate || startDate > endDate || ![15, 30, 60, 120].includes(slotMinutes)) return rpcError(payload.id, "Invalid plan fields"); const parse = (v: string) => { const [h, m] = v.split(":").map(Number); return h * 60 + m; }; if (parse(closingTime) <= parse(openingTime)) return rpcError(payload.id, "closingTime must be after openingTime"); const planId = crypto.randomUUID(); const dates: string[] = []; const cursor = new Date(`${startDate}T00:00:00Z`); const last = new Date(`${endDate}T00:00:00Z`); while (cursor <= last) { dates.push(cursor.toISOString().slice(0, 10)); cursor.setUTCDate(cursor.getUTCDate() + 1); } const rows: Array<typeof shiftSlots.$inferInsert> = []; for (const date of dates) for (let t = parse(openingTime); t + slotMinutes <= parse(closingTime); t += slotMinutes) for (const rule of rules) rows.push({ id: crypto.randomUUID(), planId, date, startTime: `${String(Math.floor(t / 60)).padStart(2, "0")}:${String(t % 60).padStart(2, "0")}`, endTime: `${String(Math.floor((t + slotMinutes) / 60)).padStart(2, "0")}:${String((t + slotMinutes) % 60).padStart(2, "0")}`, role: text(rule.role), requiredCount: Math.max(1, Number(rule.requiredCount ?? 1)) }); await db.batch([db.insert(shiftPlans).values({ id: planId, groupId, name: text(args.name), startDate, endDate, openingTime, closingTime, slotMinutes, defaultRequiredCount: Number(rules[0]?.requiredCount ?? 1), notes: text(args.notes).slice(0, 2000), status: "draft", createdBy: identity.email }), ...Array.from({ length: Math.ceil(rows.length / 8) }, (_, i) => db.insert(shiftSlots).values(rows.slice(i * 8, i * 8 + 8)))]); const period = args.requestPeriod as Record<string, unknown> | undefined; if (period && text(period.opensOn) && text(period.closesOn)) await db.insert(shiftRequestPeriods).values({ id: crypto.randomUUID(), groupId, planId, name: text(period.name, text(args.name)), opensOn: text(period.opensOn), closesOn: text(period.closesOn), status: "open", createdBy: identity.email }); return rpc(payload.id, { planId, slotCount: rows.length }); }
    if (name === "delete_draft_shift_plan") { if (args.confirm !== true) return rpcError(payload.id, mutating); const found = await planFor(db, text(args.planId), identity.email); if ("error" in found || !editorRoles.has(found.member.role)) return rpcError(payload.id, "Editor membership required"); if (found.plan.status !== "draft") return rpcError(payload.id, "Only draft plans can be deleted"); const slots = await db.select().from(shiftSlots).where(eq(shiftSlots.planId, found.plan.id)); const slotIds = slots.map((s) => s.id); await db.batch([...(slotIds.length ? [db.delete(shiftAssignments).where(inArray(shiftAssignments.slotId, slotIds))] : []), db.delete(shiftSlots).where(eq(shiftSlots.planId, found.plan.id)), db.delete(shiftRequestPeriods).where(eq(shiftRequestPeriods.planId, found.plan.id)), db.delete(shiftPlans).where(eq(shiftPlans.id, found.plan.id))]); return rpc(payload.id, { ok: true, planId: found.plan.id }); }
    if (name === "update_slot_counts") { if (args.confirm !== true) return rpcError(payload.id, mutating); const found = await planFor(db, text(args.planId), identity.email); if ("error" in found || !editorRoles.has(found.member.role)) return rpcError(payload.id, "Editor membership required"); if (found.plan.status !== "draft") return rpcError(payload.id, "Only draft plans can be adjusted"); const changes = Array.isArray(args.slots) ? args.slots as Array<Record<string, unknown>> : []; for (const change of changes) if (text(change.slotId)) await db.update(shiftSlots).set({ requiredCount: Math.max(0, Number(change.requiredCount ?? 0)) }).where(and(eq(shiftSlots.id, text(change.slotId)), eq(shiftSlots.planId, found.plan.id))); return rpc(payload.id, { ok: true, updated: changes.length, closedDates: Array.isArray(args.closedDates) ? args.closedDates : [] }); }
    if (name === "get_shift_requests") { const groupId = text(args.groupId); if (!await membership(db, groupId, identity.email)) return rpcError(payload.id, "Group membership required"); const periods = await db.select().from(shiftRequestPeriods).where(eq(shiftRequestPeriods.groupId, groupId)); const period = periods.find((p) => p.id === text(args.periodId)) ?? periods[0]; if (!period) return rpc(payload.id, { period: null, requests: [] }); return rpc(payload.id, { period, requests: await db.select().from(shiftRequests).where(and(eq(shiftRequests.periodId, period.id), eq(shiftRequests.userEmail, identity.email))) }); }
    if (name === "save_shift_requests") { if (args.confirm !== true) return rpcError(payload.id, mutating); const groupId = text(args.groupId); if (!await membership(db, groupId, identity.email)) return rpcError(payload.id, "Group membership required"); const [period] = await db.select().from(shiftRequestPeriods).where(and(eq(shiftRequestPeriods.id, text(args.periodId)), eq(shiftRequestPeriods.groupId, groupId))).limit(1); if (!period || period.status !== "open") return rpcError(payload.id, "Open request period required"); const slots = await db.select().from(shiftSlots).where(eq(shiftSlots.planId, period.planId)); const valid = new Set(slots.map((s) => `${s.date}|${s.startTime}|${s.endTime}`)); const requests = (Array.isArray(args.requests) ? args.requests : []) as Array<Record<string, unknown>>; const rows = requests.filter((r) => valid.has(`${text(r.date)}|${text(r.startTime)}|${text(r.endTime)}`) && preferenceValues.has(text(r.preference))).map((r) => ({ id: crypto.randomUUID(), periodId: period.id, userEmail: identity.email, date: text(r.date), startTime: text(r.startTime), endTime: text(r.endTime), preference: text(r.preference), note: text(r.note) })); await db.batch([db.delete(shiftRequests).where(and(eq(shiftRequests.periodId, period.id), eq(shiftRequests.userEmail, identity.email))), ...rows.map((row) => db.insert(shiftRequests).values(row))]); return rpc(payload.id, { ok: true, count: rows.length }); }
    if (name === "set_shift_assignments") { if (args.confirm !== true) return rpcError(payload.id, mutating); const found = await planFor(db, text(args.planId), identity.email); if ("error" in found || !editorRoles.has(found.member.role)) return rpcError(payload.id, "Editor membership required"); const slots = await db.select().from(shiftSlots).where(eq(shiftSlots.planId, found.plan.id)); const members = await db.select().from(groupMembers).where(and(eq(groupMembers.groupId, found.plan.groupId), eq(groupMembers.status, "active"))); const memberEmails = new Set(members.map((m) => m.userEmail)); const input = (args.assignments ?? {}) as Record<string, unknown>; const rows: Array<typeof shiftAssignments.$inferInsert> = []; for (const slot of slots) for (const email of Array.isArray(input[slot.id]) ? input[slot.id] as unknown[] : []) if (typeof email === "string" && memberEmails.has(email)) rows.push({ id: crypto.randomUUID(), slotId: slot.id, userEmail: email }); await db.batch([...(slots.length ? [db.delete(shiftAssignments).where(inArray(shiftAssignments.slotId, slots.map((s) => s.id)))] : []), ...rows.map((r) => db.insert(shiftAssignments).values(r)), db.update(shiftPlans).set({ status: args.status === "published" ? "published" : "draft" }).where(eq(shiftPlans.id, found.plan.id))]); return rpc(payload.id, { ok: true, assigned: rows.length, status: args.status === "published" ? "published" : "draft" }); }
    if (name === "list_announcements") { const groupId = text(args.groupId); if (!await membership(db, groupId, identity.email)) return rpcError(payload.id, "Group membership required"); const announcements = await db.select().from(groupAnnouncements).where(eq(groupAnnouncements.groupId, groupId)); const ids = announcements.map((a) => a.id); const replies = ids.length ? await db.select().from(announcementReplies).where(inArray(announcementReplies.announcementId, ids)) : []; const reads = ids.length ? await db.select().from(announcementReads).where(and(inArray(announcementReads.announcementId, ids), eq(announcementReads.userEmail, identity.email))) : []; return rpc(payload.id, { announcements, replies, reads }); }
    if (name === "mark_announcement_read") { const id = text(args.announcementId); const [announcement] = await db.select().from(groupAnnouncements).where(eq(groupAnnouncements.id, id)).limit(1); if (!announcement || !await membership(db, announcement.groupId, identity.email)) return rpcError(payload.id, "Announcement not found"); const [read] = await db.select().from(announcementReads).where(and(eq(announcementReads.announcementId, id), eq(announcementReads.userEmail, identity.email))).limit(1); if (!read) await db.insert(announcementReads).values({ id: crypto.randomUUID(), announcementId: id, userEmail: identity.email }); return rpc(payload.id, { ok: true, announcementId: id }); }
    if (name === "create_announcement") { if (args.confirm !== true) return rpcError(payload.id, mutating); const groupId = text(args.groupId); const member = await membership(db, groupId, identity.email); if (!member || !editorRoles.has(member.role)) return rpcError(payload.id, "Editor membership required"); const row = { id: crypto.randomUUID(), groupId, createdBy: identity.email, title: text(args.title).slice(0, 120), body: text(args.body).slice(0, 2000) }; if (!row.title || !row.body) return rpcError(payload.id, "title and body are required"); await db.insert(groupAnnouncements).values(row); return rpc(payload.id, row); }
    if (name === "reply_announcement") { const id = text(args.announcementId); const [announcement] = await db.select().from(groupAnnouncements).where(eq(groupAnnouncements.id, id)).limit(1); if (!announcement || !await membership(db, announcement.groupId, identity.email)) return rpcError(payload.id, "Announcement not found"); const row = { id: crypto.randomUUID(), announcementId: id, userEmail: identity.email, body: text(args.body).slice(0, 2000) }; if (!row.body) return rpcError(payload.id, "body is required"); await db.insert(announcementReplies).values(row); return rpc(payload.id, row); }
    if (name === "group_dashboard") { const groupId = text(args.groupId); if (!await membership(db, groupId, identity.email)) return rpcError(payload.id, "Group membership required"); const [members, plans, announcements] = await Promise.all([db.select().from(groupMembers).where(and(eq(groupMembers.groupId, groupId), eq(groupMembers.status, "active"))), db.select().from(shiftPlans).where(eq(shiftPlans.groupId, groupId)), db.select().from(groupAnnouncements).where(eq(groupAnnouncements.groupId, groupId))]); return rpc(payload.id, { memberCount: members.length, planCount: plans.length, publishedPlanCount: plans.filter((p) => p.status === "published").length, announcementCount: announcements.length }); }
    return rpcError(payload.id, `Unknown tool: ${name}`);
  } catch (caught) { return rpcError(payload.id, caught instanceof Error ? caught.message : "MCP tool failed"); }
}
